spring:
  application:
<<<<<<< HEAD
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/mulluojo
    username: postgres
=======
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mullyuojo
    username: root
>>>>>>> 92fb4c33cf5f2c9d97d49a95941d52f0216e7139
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-dates-as-timestamps: false

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


#    rabbitMQ
message:
  exchange: mullyuojo
  err:
    exchange: mullyuojo.err
  queue:
    delivery: mullyuojo.delivery
    err:
      delivery: mullyuojo.err.dlivery

