<<<<<<< HEAD
server:
  port: 19091
spring:
  autoconfigure:

  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order  # 라우트 식별자
              uri: lb://order  # 'order'라는 이름으로 로드 밸런싱된 서비스로 라우팅
              predicates:
              - Path=/orders/**  # /order/** 경로로 들어오는 요청을 이 라우트로 처리
            - id: product  #
              uri: lb://product
              predicates:
              - Path=/products/**
            - id: auth
              uri: lb://user
              predicates:
              - Path=/auth/**
            - id: user
              uri: lb://user
              predicates:
              - Path=/users/**
            - id: slack
              uri: lb://slack
              predicates:
              - Path=/slacks/**
            - id : DELIVERY-SERVICE
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/deliveries/**
            - id: hub_delivery
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/hub-delivery-channels/**
            - id: com_delivery
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/com-delivery-channels/**
            - id: delivery_user
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/delivery-users/**
            - id: company
              uri: lb://company
              predicates:
              - Path=/companies/**
            - id: hub
              uri: lb://hub
              predicates:
              - Path=/hubs/**
            - id: hub-info
              uri: lb://hub-info
              predicates:
              - Path=/hub-infos/**

    discovery:
      locator:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정


jwt:
  issuer: mulluojo-auth
  secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  accessTokenExpirationMilisec: 3600000
  refreshTokenExpirationDays: 7

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


=======
server:
  port: 19091
spring:
  autoconfigure:

  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order  # 라우트 식별자
              uri: lb://order  # 'order'라는 이름으로 로드 밸런싱된 서비스로 라우팅
              predicates:
              - Path=/orders/**  # /order/** 경로로 들어오는 요청을 이 라우트로 처리
            - id: product  #
              uri: lb://product
              predicates:
              - Path=/products/**
            - id: auth
              uri: lb://user
              predicates:
              - Path=/auth/**
            - id: user
              uri: lb://user
              predicates:
              - Path=/users/**
            - id: slack
              uri: lb://slack
              predicates:
              - Path=/slacks/**
            - id : DELIVERY-SERVICE
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/deliveries/**
            - id: hub_delivery
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/hub-delivery-channels/**
            - id: com_delivery
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/com-delivery-channels/**
            - id: delivery_user
              uri: lb://DELIVERY-SERVICE
              predicates:
              - Path=/delivery-users/**
            - id: company
              uri: lb://company
              predicates:
              - Path=/companies/**
            - id: hub
              uri: lb://hub
              predicates:
              - Path=/hubs/**
            - id: hub-info
              uri: lb://hub-info
              predicates:
              - Path=/hub-infos/**

    discovery:
      locator:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정


jwt:
  issuer: mulluojo-auth
  secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  accessTokenExpirationMilisec: 3600000
  refreshTokenExpirationDays: 7

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


>>>>>>> 92fb4c33cf5f2c9d97d49a95941d52f0216e7139
