server:
  port: 19091
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order  # 라우트 식별자
          uri: lb://order  # 'order'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/orders/**  # /order/** 경로로 들어오는 요청을 이 라우트로 처리
        - id: product  # 라우트 식별자
          uri: lb://product # 'product'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/products/**  # /product/** 경로로 들어오는 요청을 이 라우트로 처리
        - id: auth  # 라우트 식별자
          uri: lb://auth  # 'auth'라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/auth/**  # /auth/signIn 경로로 들어오는 요청을 이 라우트로 처리
    discovery:
      locator:
        enabled: true
  main:
    web-application-type: servlet

jwt:
  issuer: mulluojo-auth
  secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
  accessTokenExpirationMilisec: 3600000
  refreshTokenExpirationDays: 7